version: 1
configTables:
scriptExclusion:
  - ${EXAMPLE_DB}.${AUDIT_SCHEMA}.AUDIT_SEQ
dependencyOverride:
  - script: ${EXAMPLE_DB}.${MAIN_SCHEMA}.UPDATE_STOCK
    dependencies:
      - ${EXAMPLE_DB}.${MAIN_SCHEMA}.PRODUCTS
connection:
  account: <account>
  warehouse:  <warehouse>
  role: <role>
  db: <db>
  schema: <schema>

